### ISSUE TITLE
changes when suspense arrives mid 2019?

### ISSUE THREAD

**Issue by evdama** [CarlosGines/react-async-utils#1]
Hi Carlos,

this packages is brilliant, love it! As it's useEffect based at the moment, what do you reckon you'll change once suspense arrives? Are you going to keep the API and switch the internals to suspense assuming suspense covers the same functionality as useEffect?

I know it's a wild guess but still, reason I'm asking is that I'm thrilled by this package but then I'm certainly going to switch to either suspense or a suspense based package once suspense arrives...

**Comment by CarlosGines** [comment]
Hi Markus!

Thank you very much for the feedback! I’m really glad to know you are finding the package useful!! 😃

My intention is to keep the package relevant, updating it once Suspense lands on the stable channel. Though there are some infos about Suspense out there, and people are trying out stuff, I will definitely wait for official release and docs to include it.

About the API, my wild guess is that it will need relevant changes to make the most out of Suspense... but I cannot get wilder, not sure what it will be like!

By the way, there are still some API evolutions and new features coming in 0.13! I think you will like them :) Let me know what you think of them!

**Comment by evdama** [comment]
Excellent, one can't say more given the circumstances, but that's a rather satisfying answer.
Your package, much like https://github.com/frontarm/navi scratches a certain itch for sure! I like the idea of those four loding stages and having state defined at all times very valuable.
